# docker-compose.yml

version: "3.8"

services:

  client:
    build:
      context: ./client
    command: node /opt/yarn-v1.22.19/bin/yarn.js start
    container_name: lamaratobrowser
    ports:
      - 3003:3000
    volumes:
      - ./client:/usr/src/app
      - ./client/.env:/client/.env

  